### ISSUE TITLE
RES folder missing

### ISSUE THREAD

**Issue by timonvanhasselt** [OpenVoiceOS/ovos-technical-manual#33]
I was testing yes/no question with the Ice cream example from the OVOS technical manual (https://openvoiceos.github.io/ovos-technical-manual/500-prompts/#prompts), but I get this error from the yes_no plugin. The res folder is indeed missing. I've reinstalled it, but the res folder is not copied.

```
 13:55:17.436 - skills - ovos_plugin_manager.thirdparty.solvers:__init__:62 - DEBUG - YesNoSolver default language: en
~~~~t' : [Errno 2] No such file or directory: '/home/ovos/.venvs/ovos/lib/python3.11/site-packages/ovos_yes_no_solver/res'
 13:55:17.443 - skills - ovos_bus_client.client.client:on_default_session_update:160 - DEBUG - synced default_session
~~~~OR - [Errno 2] No such file or directory: '/home/ovos/.venvs/ovos/lib/python3.11/site-packages/ovos_yes_no_solver/res'
Traceback (most recent call last):
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/ovos_utils/events.py", line 76, in wrapper
    handler()
  File "/home/ovos/.local/share/mycroft/skills/ijs/__init__.py", line 8, in handle_do_you_like
    likes_ice_cream = self.ask_yesno('do.you.like.ice.cream')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 2048, in ask_yesno
    answer = YesNoSolver().match_yes_or_no(resp, lang=self.lang) if resp else resp
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/ovos_yes_no_solver/__init__.py", line 39, in match_yes_or_no
    _langs = os.listdir(f"{os.path.dirname(__file__)}/res")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
~~~~ror: [Errno 2] No such file or directory: '/home/ovos/.venvs/ovos/lib/python3.11/site-packages/ovos_yes_no_solver/res'
```

**Comment by timonvanhasselt** [comment]
wrong package; have to open it in yes_no plugin
